server:
  port: 8080
---
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/redislock?characterEncoding=utf-8&useSSL=false
    username: root
    password: czl19950702
    driverClassName: com.mysql.jdbc.Driver
    max-idle: 10
    max-active: 15
    max-lifetime: 86430000
    log-abandoned: true
    remove-abandoned: true
    remove-abandoned-timeout: 60
    initialize: false
    sqlScriptEncoding: UTF-8
---
spring:
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
    show-sql: true
    open-in-view: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl